included:
 - Sources
 - Tests

disabled_rules:
 - todo
 - cyclomatic_complexity
 - type_body_length
 - line_length
 - function_body_length
 - file_length
 - identifier_name
 - force_cast
 - function_parameter_count
 - override_in_extension
 - redundant_string_enum_value
 - for_where
 - blanket_disable_command

opt_in_rules:
 - private_outlet
 - private_action
 - array_init
 - convenience_type
 - discouraged_object_literal
 - empty_collection_literal
 - empty_count
 - empty_string
 - explicit_init
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - modifier_order
 - multiline_function_chains
 - operator_usage_whitespace
 - override_in_extension
 - redundant_type_annotation
 - toggle_bool
 - yoda_condition
 - conditional_returns_on_newline
 - shorthand_optional_binding

nesting:
  type_level: 2

type_name:
  max_length: 60

large_tuple:
  warning: 4
  error: 5

conditional_returns_on_newline:
  if_only: true

identifier_name:
  min_length: 3
  excluded:
  - id
  - vc
  - ip
  - pi
