on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

name: Test
jobs:
  build:
    name: Test
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      
      - name: Build
        run: swift build

      - name: Run Tests
        run: swift test
